### ISSUE TITLE
undefined method `each' for "-jekyll-angular":String

### ISSUE THREAD

**Issue by angelocordon** [JesseHerrick/jekyll-angular#1]
I'm getting this error when running jekyll serve after adding the gem in the config file

**Comment by JesseHerrick** [comment]
@angelocordon thanks for reporting this. Which version of Jekyll are you using?

**Comment by angelocordon** [comment]
hey @JesseHerrick - I'm on jekyll 2.5.3

**Comment by JesseHerrick** [comment]
Thanks. I’ll get right on it.

**Comment by JesseHerrick** [comment]
@angelocordon can you give me your Angular code as well?

**Comment by angelocordon** [comment]
I didn't have anything special - just attaching an ng-model and testing out some 2-way binding. 

``` html
    <input type="text" name="location" id="locator" placeholder="San Francisco, CA" ng-model="nglocation" />

    <span>{{ nglocation | angular }}</span>
```

**Comment by JesseHerrick** [comment]
@angelocordon, ah this isn't a bug. You need to put quotes around `nglocation`.

**e.g.**

``` html
<input type="text" name="location" id="locator" placeholder="San Francisco, CA" ng-model="nglocation" />

<span>{{ "nglocation" | angular }}</span>
```

See: https://jesse.codes/blog/Jekyll-Angular/

If you run into any more issues, let me know.

**Comment by angelocordon** [comment]
Hey Jesse, 

Still getting the same error for me, with double quotes and single quote. 

Here is my config file

```
# Build settings

markdown: kramdown
permalink: pretty
baseurl: /WhereTo

port: 3000

sass:
  sass_dir: assets/css
  style: :nested

gems:
  -jekyll-angular
```

and the full error is - 

```
→ jekyll serve --watch --baseurl ''
Configuration file: /Users/angelocordon/Development/WhereTo/_config.yml
jekyll 2.5.3 | Error:  undefined method `each' for "-jekyll-angular":String
```

Here is my repo if you need to see it - https://github.com/angelocordon/WhereTo/tree/angular

Thanks in advance!

**Comment by JesseHerrick** [comment]
@angelocordon you need a space between `-` and `jekyll-angular`.

**Comment by angelocordon** [comment]
@JesseHerrick ah, that's crazy - thanks for the help!!
