### ISSUE TITLE
Jekyll-Angular not working?

### ISSUE THREAD

**Issue by frucht-salat** [JesseHerrick/jekyll-angular#2]
Hello, I tried out your plugin:

```html
<p> Text </p>

<div ng-app="testApp" ng-controller="appCtrl">
        <p> Name: <input type="text" ng-model="characterName"> </p>
        <br>
        <p> So you are called: {% raw %} {{ characterName }} {% endraw %} ? </p>
        <p> Or are you called: {{ 'characterName' | angular }} </p>
</div>

<script type="text/javascript">
        console.log("foo");
        var app = angular.module('testApp', []);
        app.controller('appCtrl', function($scope) {
        $scope.characterName= "Nyana";
        });
</script>
```

The part with raw is working, but the | angular one is not. There ist just "characterName" displayed 
What could I do wrong?

**Comment by JesseHerrick** [comment]
Hi @Zujiry,

Are you sure that you have the gem installed properly? Jekyll changed the way it loads plugins, so they must be loaded under `plugins` rather than `gems` now in your `_config.yml`.

**Comment by TheComputerM** [comment]
Try to add **_gem 'jekyll-angular', '~> 0.1.1'_** in the GemFile
