### ISSUE TITLE
Error in documentation (README)

### ISSUE THREAD

**Issue by TheComputerM** [JesseHerrick/jekyll-angular#3]
You also have to include **gem 'jekyll-angular', '~> 0.1.1'** in the GemFile.

It is not mentioned in the documentation.

Line to include: **gem 'jekyll-angular', '~> 0.1.1'**

**Comment by JesseHerrick** [comment]
Sorry about that. Thanks for bringing this to my attention. I've added a line in the README about adding it to your Gemfile.
